// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"time"

	"github.com/gofrs/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Job struct {
	ID            uuid.UUID   `json:"id"`
	UserID        uuid.UUID   `json:"user_id"`
	Company       string      `json:"company"`
	PositionDesc  string      `json:"position_desc"`
	Remote        pgtype.Bool `json:"remote"`
	ContractType  string      `json:"contract_type"`
	Contacted     pgtype.Bool `json:"contacted"`
	GeneralStatus string      `json:"general_status"`
	CreatedAt     time.Time   `json:"created_at"`
	UpdatedAt     time.Time   `json:"updated_at"`
	Comments      pgtype.Text `json:"comments"`
}

type User struct {
	ID        uuid.UUID   `json:"id"`
	Name      pgtype.Text `json:"name"`
	Email     string      `json:"email"`
	Photo     string      `json:"photo"`
	CreatedAt time.Time   `json:"created_at"`
	UpdatedAt time.Time   `json:"updated_at"`
}
